name: Run Tests

on:
  push:
    branches-ignore: [master, main]

jobs:
  TestAllModes:
  name: Testing ${{ matrix.testMode }}
  runs-on: ubuntu-latest
      strategy:
      fail-fast: false
      matrix:
        projectPath:
          - test-project
        testMode:
          - playmode
          - editmode
          - standalone
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v2
        with:
          path: ./Library
          key: Library-Space-Rescue-StandaloneWindows
          restore-keys: |
            Library-Space-Rescue-
            Library-
      - uses: game-ci/unity-test-runner@v3.0.0
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ matrix.testMode }} Test Results
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}
