---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Validate Code Base

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore: [master, main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, main]
    
  workflow_dispatch:
###############
# Set the Job #
###############
jobs:
  Validate-Codebase:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: Get Changed Files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} HEAD)
          echo "::set-output name=changed_files::$CHANGED_FILES"
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Analyze Changed Files
        run: |
          changed_files=${{ steps.changed-files.outputs.changed_files }}
          for file in $changed_files; do
            echo "$file"
            dotnet-format -f "$file" --check 
          done

        
