---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Validate Code Base

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore: [master, main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, main]
    
  workflow_dispatch:
###############
# Set the Job #
###############
jobs:
  resharper:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      # MegaLinter
      - name: MegaLinter
        id: ml
        # You can override MegaLinter flavor used to have faster performances
        # More info at https://megalinter.io/flavors/
        uses: oxsecurity/megalinter@v7
        env:
          # All available variables are described in documentation
          # https://megalinter.io/configuration/
          VALIDATE_ALL_CODEBASE: false
          ENABLE_LINTERS: CSHARPIER
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
