---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Validate Code Base

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore: [master, main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, main]
    
  workflow_dispatch:
###############
# Set the Job #
###############
jobs:
  Validate-Codebase:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
        
      - name: Get Changed Files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff ${{ github.event.before }} HEAD --name-only)
          echo "::set-output name=changed_files::$CHANGED_FILES"
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Analyze Changed Files
        run: |
          changed_files=${{ steps.changed-files.outputs.changed_files }}
          for file in $changed_files; do
              if [[ $file == *.cs ]]; then
                dotnet format -f "$file" --check
              fi
]         done

        
